include:
  # 通常構成（左右）
  - board: bmp_boost
    shield: torabo_tsuki_lp_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: torabo_tsuki_lp_left_central

  - board: bmp_boost
    shield: torabo_tsuki_lp_right
    snippet: studio-rpc-usb-uart
    artifact-name: torabo_tsuki_lp_right_peripheral

  - board: bmp_boost
    shield: torabo_tsuki_lp_left
    snippet: studio-rpc-usb-uart
    artifact-name: torabo_tsuki_lp_left_peripheral

  - board: bmp_boost
    shield: torabo_tsuki_lp_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: torabo_tsuki_lp_right_central

  # トラックパッド構成（左手 Peripheral）
  - board: bmp_boost
    shield: torabo_tsuki_lp_left
    snippet: studio-rpc-usb-uart split-trackpad
    artifact-name: torabo_tsuki_lp_left_peripheral_trackpad
    cmake-args: -DKEYMAP_FILE=keymap.trackpad.keymap

  # トラックパッド構成（右手 Central）
  - board: bmp_boost
    shield: torabo_tsuki_lp_right
    snippet: studio-rpc-usb-uart split-trackpad-listner
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DKEYMAP_FILE=keymap.trackpad.keymap
    artifact-name: torabo_tsuki_lp_right_central_trackpad

  # 設定リセット
  - board: bmp_boost
    shield: settings_reset
